name: .grupo-00-venv
channels:
  - conda-forge
dependencies:
  - python==3.10.6
  - pandas
  - numpy
  - matplotlib
  - nbformat
  - ipykernel
  - openpyxl
  - scikit-learn
  - keras
  - tensorflow
  - pip
  - seaborn
  - plotly